version: 2.1
jobs:
    publish:
        docker:
            - image: cimg/node:18.4.0
        description: Build and push image to Google Container Registry
        steps:
            - checkout
            - run: npm ci
            - run: npm test
            - run:
                command: |
                  npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
                  npm run release
workflows:
  tagged-build:
    jobs:
      - publish:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
